CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE "Users" (
    "Id" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "FullName" character varying(100) NOT NULL,
    "Email" character varying(100) NOT NULL,
    "PasswordHash" text NOT NULL,
    "PasswordSalt" text NOT NULL,
    "AvatarURL" character varying(500),
    "Role" character varying(20) NOT NULL,
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    "DataEncryptionKey" text,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "RefreshToken" text,
    "RefreshTokenExpiryTime" timestamp with time zone,
    "PasswordResetToken" text,
    "PasswordResetTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Users_Role" CHECK ("Role" IN ('Admin','Author','Staff'))
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224203002_InitialCreate', '9.0.2');

COMMIT;

-- ============================================================
-- Migration: AddProjectsTable
-- ============================================================

START TRANSACTION;

CREATE TABLE "Projects" (
    "Id" uuid NOT NULL DEFAULT (uuid_generate_v4()),
    "AuthorId" uuid NOT NULL,
    "EncryptedTitle" text NOT NULL,
    "EncryptedSummary" text,
    "CoverImageURL" character varying(500),
    "Status" character varying(20) NOT NULL DEFAULT 'Draft',
    "IsDeleted" boolean NOT NULL DEFAULT FALSE,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT (NOW()),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Projects_Status" CHECK ("Status" IN ('Draft','Published','Archived')),
    CONSTRAINT "FK_Projects_Users_AuthorId" FOREIGN KEY ("AuthorId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Projects_AuthorId" ON "Projects" ("AuthorId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260225094534_AddProjectsTable', '9.0.2');

COMMIT;

-- ============================================================
-- Migration: AddSubscriptionTables
-- Applied: 2026-02-26
-- ============================================================

START TRANSACTION;

CREATE TABLE "SubscriptionPlans" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY,
    "PlanName" character varying(50) NOT NULL,
    "Price" numeric(18,2) NOT NULL DEFAULT 0,
    "MaxAnalysisCount" integer NOT NULL DEFAULT 10,
    "MaxTokenLimit" bigint NOT NULL DEFAULT 50000,
    "Description" text,
    "IsActive" boolean NOT NULL DEFAULT TRUE
);

CREATE TABLE "UserSubscriptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY CONSTRAINT "PK_UserSubscriptions" PRIMARY KEY,
    "UserId" uuid NOT NULL,
    "PlanId" integer NOT NULL,
    "StartDate" timestamp with time zone NOT NULL,
    "EndDate" timestamp with time zone NOT NULL,
    "Status" character varying(20) NOT NULL DEFAULT 'Active',
    "UsedAnalysisCount" integer NOT NULL DEFAULT 0,
    "UsedTokens" bigint NOT NULL DEFAULT 0,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "CK_UserSub_Status" CHECK ("Status" IN ('Active','Expired','Cancelled')),
    CONSTRAINT "FK_UserSubscriptions_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSubscriptions_SubscriptionPlans_PlanId" FOREIGN KEY ("PlanId")
        REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_UserSubscriptions_UserId" ON "UserSubscriptions" ("UserId");
CREATE INDEX "IX_UserSubscriptions_PlanId" ON "UserSubscriptions" ("PlanId");

-- Seed data
INSERT INTO "SubscriptionPlans" ("Id","PlanName","Price","MaxAnalysisCount","MaxTokenLimit","Description","IsActive") VALUES
    (1, 'Free',       0,      3,    20000,   N'Goi mien phi – 3 lan phan tich bo truyen va 20,000 token AI moi thang.',         TRUE),
    (2, 'Basic',      99000,  20,   150000,  N'Goi co ban – 99,000d/thang. 20 lan phan tich va 150,000 token AI.',              TRUE),
    (3, 'Pro',        249000, 100,  500000,  N'Goi chuyen nghiep – 249,000d/thang. 100 lan phan tich va 500,000 token AI.',     TRUE),
    (4, 'Enterprise', 699000, 9999, 2000000, N'Goi doanh nghiep – 699,000d/thang. Khong gioi han phan tich va 2,000,000 token AI.', TRUE);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260226114705_AddSubscriptionTables', '9.0.2');

COMMIT;
