-- ============================================================
-- StoryRAG — Full Reset & Init
-- Xóa toàn bộ tables + data, tạo lại từ đầu theo schema mới nhất.
-- Chạy file này trên Supabase SQL Editor.
-- Sau khi chạy, EF sẽ KHÔNG cần migrate lại (history đã được ghi sẵn).
-- ============================================================

-- ────────────────────────────────────────────────────────────
-- BƯỚC 1: XÓA TOÀN BỘ (CASCADE để tránh lỗi FK)
-- ────────────────────────────────────────────────────────────

DROP TABLE IF EXISTS "RewriteHistories"      CASCADE;
DROP TABLE IF EXISTS "ChatMessages"          CASCADE;
DROP TABLE IF EXISTS "WorldbuildingEntries"  CASCADE;
DROP TABLE IF EXISTS "CharacterEntries"      CASCADE;
DROP TABLE IF EXISTS "UserSettings"          CASCADE;
DROP TABLE IF EXISTS "ProjectReports"        CASCADE;
DROP TABLE IF EXISTS "ProjectGenres"         CASCADE;
DROP TABLE IF EXISTS "ChapterChunks"         CASCADE;
DROP TABLE IF EXISTS "ChapterVersions"       CASCADE;
DROP TABLE IF EXISTS "Chapters"              CASCADE;
DROP TABLE IF EXISTS "UserSubscriptions"     CASCADE;
DROP TABLE IF EXISTS "Projects"              CASCADE;
DROP TABLE IF EXISTS "SubscriptionPlans"     CASCADE;
DROP TABLE IF EXISTS "Genres"                CASCADE;
DROP TABLE IF EXISTS "Users"                 CASCADE;
DROP TABLE IF EXISTS "__EFMigrationsHistory" CASCADE;

-- ────────────────────────────────────────────────────────────
-- BƯỚC 2: EXTENSIONS
-- ────────────────────────────────────────────────────────────

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS vector;

-- ────────────────────────────────────────────────────────────
-- BƯỚC 3: EF MIGRATIONS HISTORY
-- ────────────────────────────────────────────────────────────

CREATE TABLE "__EFMigrationsHistory" (
    "MigrationId"    character varying(150) NOT NULL,
    "ProductVersion" character varying(32)  NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

-- ────────────────────────────────────────────────────────────
-- BƯỚC 4: TẠO TABLES (theo thứ tự dependency)
-- ────────────────────────────────────────────────────────────

-- ── Users ────────────────────────────────────────────────────
CREATE TABLE "Users" (
    "Id"                           uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "FullName"                     character varying(100)   NOT NULL,
    "Email"                        character varying(100)   NOT NULL,
    "PasswordHash"                 text                     NOT NULL,
    "PasswordSalt"                 text                     NOT NULL,
    "AvatarURL"                    character varying(500),
    "Role"                         character varying(20)    NOT NULL,
    "IsActive"                     boolean                  NOT NULL DEFAULT TRUE,
    "DataEncryptionKey"            text,
    "CreatedAt"                    timestamp with time zone NOT NULL DEFAULT NOW(),
    "RefreshToken"                 text,
    "RefreshTokenExpiryTime"       timestamp with time zone,
    "PasswordResetToken"           text,
    "PasswordResetTokenExpiryTime" timestamp with time zone,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Users_Role" CHECK ("Role" IN ('Admin','Author','Staff'))
);

CREATE UNIQUE INDEX "IX_Users_Email" ON "Users" ("Email");

-- ── SubscriptionPlans ────────────────────────────────────────
CREATE TABLE "SubscriptionPlans" (
    "Id"               integer          GENERATED BY DEFAULT AS IDENTITY,
    "PlanName"         character varying(50)    NOT NULL,
    "Price"            numeric(18,2)            NOT NULL DEFAULT 0,
    "MaxAnalysisCount" integer                  NOT NULL DEFAULT 10,
    "MaxTokenLimit"    bigint                   NOT NULL DEFAULT 50000,
    "Description"      text,
    "IsActive"         boolean                  NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_SubscriptionPlans" PRIMARY KEY ("Id")
);

-- ── Genres ───────────────────────────────────────────────────
CREATE TABLE "Genres" (
    "Id"          integer                  GENERATED BY DEFAULT AS IDENTITY,
    "Name"        character varying(100)   NOT NULL,
    "Slug"        character varying(100)   NOT NULL,
    "Color"       character varying(20)    NOT NULL DEFAULT '#6366f1',
    "Description" character varying(500),
    CONSTRAINT "PK_Genres" PRIMARY KEY ("Id")
);

CREATE UNIQUE INDEX "IX_Genres_Slug" ON "Genres" ("Slug");

-- ── Projects ─────────────────────────────────────────────────
CREATE TABLE "Projects" (
    "Id"            uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "AuthorId"      uuid                     NOT NULL,
    "Title"         text                     NOT NULL,
    "Summary"       text,
    "CoverImageURL" character varying(500),
    "Status"        character varying(20)    NOT NULL DEFAULT 'Draft',
    "IsDeleted"     boolean                  NOT NULL DEFAULT FALSE,
    "CreatedAt"     timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt"     timestamp with time zone,
    CONSTRAINT "PK_Projects" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Projects_Status" CHECK ("Status" IN ('Draft','Published','Archived')),
    CONSTRAINT "FK_Projects_Users_AuthorId" FOREIGN KEY ("AuthorId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_Projects_AuthorId" ON "Projects" ("AuthorId");

-- ── UserSubscriptions ────────────────────────────────────────
CREATE TABLE "UserSubscriptions" (
    "Id"                integer                  GENERATED BY DEFAULT AS IDENTITY,
    "UserId"            uuid                     NOT NULL,
    "PlanId"            integer                  NOT NULL,
    "StartDate"         timestamp with time zone NOT NULL,
    "EndDate"           timestamp with time zone NOT NULL,
    "Status"            character varying(20)    NOT NULL DEFAULT 'Active',
    "UsedAnalysisCount" integer                  NOT NULL DEFAULT 0,
    "UsedTokens"        bigint                   NOT NULL DEFAULT 0,
    "CreatedAt"         timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_UserSubscriptions" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_UserSub_Status" CHECK ("Status" IN ('Active','Expired','Cancelled')),
    CONSTRAINT "FK_UserSubscriptions_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_UserSubscriptions_SubscriptionPlans_PlanId" FOREIGN KEY ("PlanId")
        REFERENCES "SubscriptionPlans" ("Id") ON DELETE RESTRICT
);

CREATE INDEX "IX_UserSubscriptions_UserId"  ON "UserSubscriptions" ("UserId");
CREATE INDEX "IX_UserSubscriptions_PlanId"  ON "UserSubscriptions" ("PlanId");

-- ── ProjectGenres ────────────────────────────────────────────
CREATE TABLE "ProjectGenres" (
    "ProjectId" uuid    NOT NULL,
    "GenreId"   integer NOT NULL,
    CONSTRAINT "PK_ProjectGenres" PRIMARY KEY ("ProjectId", "GenreId"),
    CONSTRAINT "FK_ProjectGenres_Projects_ProjectId" FOREIGN KEY ("ProjectId")
        REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProjectGenres_Genres_GenreId" FOREIGN KEY ("GenreId")
        REFERENCES "Genres" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ProjectGenres_GenreId" ON "ProjectGenres" ("GenreId");

-- ── ChapterVersions (tạo trước để Chapters có thể FK vào) ───
-- Tạm thời chưa có FK ngược từ Chapters → ChapterVersions
CREATE TABLE "ChapterVersions" (
    "Id"            uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "ChapterId"     uuid                     NOT NULL,
    "VersionNumber" integer                  NOT NULL,
    "Content"       text                     NOT NULL,
    "ChangeNote"    text,
    "WordCount"     integer                  NOT NULL DEFAULT 0,
    "TokenCount"    integer                  NOT NULL DEFAULT 0,
    "CreatedBy"     uuid                     NOT NULL,
    "IsChunked"     boolean                  NOT NULL DEFAULT FALSE,
    "IsEmbedded"    boolean                  NOT NULL DEFAULT FALSE,
    "Title"         character varying(255),
    "UpdatedAt"     timestamp with time zone,
    "CreatedAt"     timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ChapterVersions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChapterVersions_Users_CreatedBy" FOREIGN KEY ("CreatedBy")
        REFERENCES "Users" ("Id") ON DELETE RESTRICT
    -- FK_ChapterVersions_Chapters sẽ thêm sau khi tạo bảng Chapters
);

-- ── Chapters ─────────────────────────────────────────────────
CREATE TABLE "Chapters" (
    "Id"                uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "ProjectId"         uuid                     NOT NULL,
    "ChapterNumber"     integer                  NOT NULL,
    "Title"             character varying(255),
    "WordCount"         integer                  NOT NULL DEFAULT 0,
    "Status"            character varying(20)    NOT NULL DEFAULT 'Draft',
    "CurrentVersionId"  uuid,
    "CurrentVersionNum" integer                  NOT NULL DEFAULT 0,
    "IsDeleted"         boolean                  NOT NULL DEFAULT FALSE,
    "DraftContent"      text,
    "DraftSavedAt"      timestamp with time zone,
    "CreatedAt"         timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt"         timestamp with time zone,
    CONSTRAINT "PK_Chapters" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_Chapters_Status" CHECK ("Status" IN ('Draft','Final','Archived')),
    CONSTRAINT "FK_Chapters_Projects" FOREIGN KEY ("ProjectId")
        REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Chapters_CurrentVersion" FOREIGN KEY ("CurrentVersionId")
        REFERENCES "ChapterVersions" ("Id") ON DELETE SET NULL
);

CREATE UNIQUE INDEX "UQ_Chapter_Number"   ON "Chapters" ("ProjectId", "ChapterNumber") WHERE "IsDeleted" = FALSE;
CREATE INDEX        "IX_Chapters_ProjectId"      ON "Chapters" ("ProjectId");
CREATE INDEX        "IX_Chapters_CurrentVersionId" ON "Chapters" ("CurrentVersionId");

-- Thêm FK ngược từ ChapterVersions → Chapters (circular, phải sau khi Chapters tồn tại)
ALTER TABLE "ChapterVersions"
    ADD CONSTRAINT "FK_ChapterVersions_Chapters_ChapterId" FOREIGN KEY ("ChapterId")
        REFERENCES "Chapters" ("Id") ON DELETE CASCADE;

CREATE UNIQUE INDEX "UQ_ChapterVersions"          ON "ChapterVersions" ("ChapterId", "VersionNumber");
CREATE INDEX        "IX_ChapterVersions_ChapterId" ON "ChapterVersions" ("ChapterId");
CREATE INDEX        "IX_ChapterVersions_CreatedBy" ON "ChapterVersions" ("CreatedBy");

-- ── ChapterChunks ─────────────────────────────────────────────
CREATE TABLE "ChapterChunks" (
    "Id"         uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "VersionId"  uuid                     NOT NULL,
    "ProjectId"  uuid                     NOT NULL,
    "ChunkIndex" integer                  NOT NULL,
    "Content"    text                     NOT NULL,
    "TokenCount" integer                  NOT NULL DEFAULT 0,
    "Embedding"  vector(768),
    "CreatedAt"  timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ChapterChunks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChapterChunks_Versions_VersionId" FOREIGN KEY ("VersionId")
        REFERENCES "ChapterVersions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChapterChunks_Projects_ProjectId" FOREIGN KEY ("ProjectId")
        REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChapterChunks_VersionId"  ON "ChapterChunks" ("VersionId");
CREATE INDEX "IX_ChapterChunks_ProjectId"  ON "ChapterChunks" ("ProjectId");

-- IVFFlat index cho vector search (uncomment sau khi có >= 100 rows embedding)
-- CREATE INDEX "IX_ChapterChunks_Embedding" ON "ChapterChunks"
--     USING ivfflat ("Embedding" vector_cosine_ops) WITH (lists = 100);

-- ── UserSettings ─────────────────────────────────────────────
CREATE TABLE "UserSettings" (
    "UserId"         uuid                  NOT NULL,
    "EditorFont"     character varying(100) NOT NULL DEFAULT 'Be Vietnam Pro',
    "EditorFontSize" integer               NOT NULL DEFAULT 17,
    CONSTRAINT "PK_UserSettings" PRIMARY KEY ("UserId"),
    CONSTRAINT "FK_UserSettings_Users" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- ── ProjectReports ────────────────────────────────────────────
CREATE TABLE "ProjectReports" (
    "Id"           uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "ProjectId"    uuid                     NOT NULL,
    "UserId"       uuid                     NOT NULL,
    "Status"       character varying(20)    NOT NULL DEFAULT 'Pending',
    "TotalScore"   numeric(5,2)             NOT NULL DEFAULT 0,
    "CriteriaJson" jsonb                    NOT NULL DEFAULT '[]',
    "CreatedAt"    timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt"    timestamp with time zone,
    CONSTRAINT "PK_ProjectReports" PRIMARY KEY ("Id"),
    CONSTRAINT "CK_ProjectReports_Status" CHECK ("Status" IN ('Pending','Completed','Failed','MockData')),
    CONSTRAINT "FK_ProjectReports_Projects" FOREIGN KEY ("ProjectId") REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ProjectReports_Users"    FOREIGN KEY ("UserId")    REFERENCES "Users"    ("Id") ON DELETE CASCADE
);

-- ── WorldbuildingEntries ──────────────────────────────────────
CREATE TABLE "WorldbuildingEntries" (
    "Id"        uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "ProjectId" uuid                     NOT NULL,
    "Title"     text                     NOT NULL,
    "Content"   text                     NOT NULL DEFAULT '',
    "Category"  character varying(50)    NOT NULL DEFAULT 'Other',
    "Embedding" vector(768),
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt" timestamp with time zone,
    CONSTRAINT "PK_WorldbuildingEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_WorldbuildingEntries_Projects_ProjectId" FOREIGN KEY ("ProjectId")
        REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_WorldbuildingEntries_ProjectId" ON "WorldbuildingEntries" ("ProjectId");

-- IVFFlat index cho vector search (uncomment sau khi có >= 100 rows embedding)
-- CREATE INDEX "IX_WorldbuildingEntries_Embedding" ON "WorldbuildingEntries"
--     USING ivfflat ("Embedding" vector_cosine_ops) WITH (lists = 100);

-- ── CharacterEntries ──────────────────────────────────────────
CREATE TABLE "CharacterEntries" (
    "Id"          uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "ProjectId"   uuid                     NOT NULL,
    "Name"        text                     NOT NULL,
    "Role"        character varying(50)    NOT NULL DEFAULT 'Supporting',
    "Description" text                     NOT NULL DEFAULT '',
    "Background"  text,
    "Notes"       text,
    "Embedding"   vector(768),
    "CreatedAt"   timestamp with time zone NOT NULL DEFAULT NOW(),
    "UpdatedAt"   timestamp with time zone,
    CONSTRAINT "PK_CharacterEntries" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_CharacterEntries_Projects_ProjectId" FOREIGN KEY ("ProjectId")
        REFERENCES "Projects" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_CharacterEntries_ProjectId" ON "CharacterEntries" ("ProjectId");

-- IVFFlat index cho vector search (uncomment sau khi có >= 100 rows embedding)
-- CREATE INDEX "IX_CharacterEntries_Embedding" ON "CharacterEntries"
--     USING ivfflat ("Embedding" vector_cosine_ops) WITH (lists = 100);

-- ── ChatMessages ──────────────────────────────────────────────
CREATE TABLE "ChatMessages" (
    "Id"           uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "ProjectId"    uuid                     NOT NULL,
    "UserId"       uuid                     NOT NULL,
    "Question"     text                     NOT NULL,
    "Answer"       text                     NOT NULL,
    "InputTokens"  integer                  NOT NULL DEFAULT 0,
    "OutputTokens" integer                  NOT NULL DEFAULT 0,
    "TotalTokens"  integer                  NOT NULL DEFAULT 0,
    "CreatedAt"    timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_ChatMessages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatMessages_Projects_ProjectId" FOREIGN KEY ("ProjectId")
        REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ChatMessages_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_ChatMessages_ProjectId_UserId" ON "ChatMessages" ("ProjectId", "UserId");
CREATE INDEX "IX_ChatMessages_UserId"           ON "ChatMessages" ("UserId");

-- ── RewriteHistories ──────────────────────────────────────────
CREATE TABLE "RewriteHistories" (
    "Id"            uuid                     NOT NULL DEFAULT (uuid_generate_v4()),
    "ProjectId"     uuid                     NOT NULL,
    "ChapterId"     uuid,
    "UserId"        uuid                     NOT NULL,
    "OriginalText"  text                     NOT NULL,
    "RewrittenText" text                     NOT NULL,
    "Instruction"   text                     NOT NULL DEFAULT '',
    "TotalTokens"   integer                  NOT NULL DEFAULT 0,
    "CreatedAt"     timestamp with time zone NOT NULL DEFAULT NOW(),
    CONSTRAINT "PK_RewriteHistories" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_RewriteHistories_Projects_ProjectId" FOREIGN KEY ("ProjectId")
        REFERENCES "Projects" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_RewriteHistories_Chapters_ChapterId" FOREIGN KEY ("ChapterId")
        REFERENCES "Chapters" ("Id") ON DELETE SET NULL,
    CONSTRAINT "FK_RewriteHistories_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_RewriteHistories_ProjectId_UserId" ON "RewriteHistories" ("ProjectId", "UserId");
CREATE INDEX "IX_RewriteHistories_UserId"            ON "RewriteHistories" ("UserId");
CREATE INDEX "IX_RewriteHistories_ChapterId"         ON "RewriteHistories" ("ChapterId");

-- ────────────────────────────────────────────────────────────
-- BƯỚC 5: SEED DATA
-- ────────────────────────────────────────────────────────────

-- Subscription Plans
INSERT INTO "SubscriptionPlans" ("Id","PlanName","Price","MaxAnalysisCount","MaxTokenLimit","Description","IsActive") VALUES
    (1, 'Free',       0,       3,    20000,   'Gói miễn phí – 3 lần phân tích bộ truyện và 20,000 token AI mỗi tháng.',         TRUE),
    (2, 'Basic',      99000,   20,   150000,  'Gói cơ bản – 99,000đ/tháng. 20 lần phân tích và 150,000 token AI.',              TRUE),
    (3, 'Pro',        249000,  100,  500000,  'Gói chuyên nghiệp – 249,000đ/tháng. 100 lần phân tích và 500,000 token AI.',     TRUE),
    (4, 'Enterprise', 699000,  9999, 2000000, 'Gói doanh nghiệp – 699,000đ/tháng. Không giới hạn phân tích và 2,000,000 token AI.', TRUE);

-- Reset sequence sau khi insert tường minh
SELECT setval(pg_get_serial_sequence('"SubscriptionPlans"', 'Id'), 4);

-- Genres
INSERT INTO "Genres" ("Id","Name","Slug","Color","Description") VALUES
    (1,  'Tiểu thuyết',         'tieu-thuyet',         '#6366f1', 'Tác phẩm văn xuôi dài'),
    (2,  'Ngắn truyện',         'ngan-truyen',          '#8b5cf6', 'Truyện ngắn, truyện vừa'),
    (3,  'Kiếm hiệp',           'kiem-hiep',            '#ef4444', 'Võ hiệp, kiếm khách'),
    (4,  'Tiên hiệp',           'tien-hiep',            '#f59e0b', 'Tu tiên, luyện khí'),
    (5,  'Huyền huyễn',         'huyen-huyen',          '#10b981', 'Fantasy, thế giới ảo'),
    (6,  'Khoa học viễn tưởng', 'khoa-hoc-vien-tuong', '#3b82f6', 'Sci-Fi, tương lai'),
    (7,  'Lãng mạn',            'lang-man',             '#ec4899', 'Tình cảm, lãng mạn'),
    (8,  'Trinh thám',          'trinh-tham',           '#64748b', 'Điều tra, phá án'),
    (9,  'Kinh dị',             'kinh-di',              '#dc2626', 'Horror, ma quái'),
    (10, 'Lịch sử',             'lich-su',              '#92400e', 'Bối cảnh lịch sử'),
    (11, 'Đô thị',              'do-thi',               '#0891b2', 'Cuộc sống hiện đại'),
    (12, 'Xuyên không',         'xuyen-khong',          '#7c3aed', 'Isekai, xuyên thời gian'),
    (13, 'Hệ thống',            'he-thong',             '#059669', 'LitRPG, hệ thống cấp bậc'),
    (14, 'Gia đình',            'gia-dinh',             '#d97706', 'Tình cảm gia đình');

SELECT setval(pg_get_serial_sequence('"Genres"', 'Id'), 14);

-- ────────────────────────────────────────────────────────────
-- BƯỚC 6: GHI EF MIGRATIONS HISTORY
-- (EF sẽ không chạy lại các migration này)
-- ────────────────────────────────────────────────────────────

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion") VALUES
    ('20260224203002_InitialCreate',              '9.0.2'),
    ('20260225094534_AddProjectsTable',           '9.0.2'),
    ('20260225110717_RenameProjectColumns',       '9.0.2'),
    ('20260226114705_AddSubscriptionTables',      '9.0.2'),
    ('20260227091028_Phase2_EmbeddingVector768',  '9.0.2'),
    ('20260227102011_AddGenres',                  '9.0.2'),
    ('20260227105604_AddChapterDraft',            '9.0.2'),
    ('20260227115512_UpdateChapterVersionSchema', '9.0.2'),
    ('20260228113206_AddProjectReports',          '9.0.2'),
    ('20260228115136_AddUserSettings',            '9.0.2'),
    ('20260308053133_AddWorldbuildingAndCharacter','9.0.2'),
    ('20260311090848_AddChatHistory',             '9.0.2'),
    ('20260311100332_AddRewriteHistory',          '9.0.2');
