// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;
using Repository.Data;

#nullable disable

namespace Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228113206_AddProjectReports")]
    partial class AddProjectReports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Repository.Entities.Chapter", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid?>("CurrentVersionId")
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentVersionNum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("DraftContent")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DraftSavedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CurrentVersionId");

                    b.HasIndex("ProjectId", "ChapterNumber")
                        .IsUnique();

                    b.ToTable("Chapters", t =>
                        {
                            t.HasCheckConstraint("CK_Chapters_Status", "\"Status\" IN ('Draft','Final','Archived')");
                        });
                });

            modelBuilder.Entity("Repository.Entities.ChapterChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("TokenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("VersionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.HasIndex("VersionId");

                    b.ToTable("ChapterChunks");
                });

            modelBuilder.Entity("Repository.Entities.ChapterVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("text");

                    b.Property<Guid>("ChapterId")
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsChunked")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsEmbedded")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("TokenCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("integer");

                    b.Property<int>("WordCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ChapterId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("ChapterVersions");
                });

            modelBuilder.Entity("Repository.Entities.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("#6366f1");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#6366f1",
                            Description = "Tác phẩm văn xuôi dài",
                            Name = "Tiểu thuyết",
                            Slug = "tieu-thuyet"
                        },
                        new
                        {
                            Id = 2,
                            Color = "#8b5cf6",
                            Description = "Truyện ngắn, truyện vừa",
                            Name = "Ngắn truyện",
                            Slug = "ngan-truyen"
                        },
                        new
                        {
                            Id = 3,
                            Color = "#ef4444",
                            Description = "Võ hiệp, kiếm khách",
                            Name = "Kiếm hiệp",
                            Slug = "kiem-hiep"
                        },
                        new
                        {
                            Id = 4,
                            Color = "#f59e0b",
                            Description = "Tu tiên, luyện khí",
                            Name = "Tiên hiệp",
                            Slug = "tien-hiep"
                        },
                        new
                        {
                            Id = 5,
                            Color = "#10b981",
                            Description = "Fantasy, thế giới ảo",
                            Name = "Huyền huyễn",
                            Slug = "huyen-huyen"
                        },
                        new
                        {
                            Id = 6,
                            Color = "#3b82f6",
                            Description = "Sci-Fi, tương lai",
                            Name = "Khoa học viễn tưởng",
                            Slug = "khoa-hoc-vien-tuong"
                        },
                        new
                        {
                            Id = 7,
                            Color = "#ec4899",
                            Description = "Tình cảm, lãng mạn",
                            Name = "Lãng mạn",
                            Slug = "lang-man"
                        },
                        new
                        {
                            Id = 8,
                            Color = "#64748b",
                            Description = "Điều tra, phá án",
                            Name = "Trinh thám",
                            Slug = "trinh-tham"
                        },
                        new
                        {
                            Id = 9,
                            Color = "#dc2626",
                            Description = "Horror, ma quái",
                            Name = "Kinh dị",
                            Slug = "kinh-di"
                        },
                        new
                        {
                            Id = 10,
                            Color = "#92400e",
                            Description = "Bối cảnh lịch sử",
                            Name = "Lịch sử",
                            Slug = "lich-su"
                        },
                        new
                        {
                            Id = 11,
                            Color = "#0891b2",
                            Description = "Cuộc sống hiện đại",
                            Name = "Đô thị",
                            Slug = "do-thi"
                        },
                        new
                        {
                            Id = 12,
                            Color = "#7c3aed",
                            Description = "Isekai, xuyên thời gian",
                            Name = "Xuyên không",
                            Slug = "xuyen-khong"
                        },
                        new
                        {
                            Id = 13,
                            Color = "#059669",
                            Description = "LitRPG, hệ thống cấp bậc",
                            Name = "Hệ thống",
                            Slug = "he-thong"
                        },
                        new
                        {
                            Id = 14,
                            Color = "#d97706",
                            Description = "Tình cảm gia đình",
                            Name = "Gia đình",
                            Slug = "gia-dinh"
                        });
                });

            modelBuilder.Entity("Repository.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CoverImageURL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Draft");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Projects", t =>
                        {
                            t.HasCheckConstraint("CK_Projects_Status", "\"Status\" IN ('Draft','Published','Archived')");
                        });
                });

            modelBuilder.Entity("Repository.Entities.ProjectGenre", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uuid");

                    b.Property<int>("GenreId")
                        .HasColumnType("integer");

                    b.HasKey("ProjectId", "GenreId");

                    b.HasIndex("GenreId");

                    b.ToTable("ProjectGenres");
                });

            modelBuilder.Entity("Repository.Entities.SubscriptionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxAnalysisCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(10);

                    b.Property<long>("MaxTokenLimit")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(50000L);

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("Price")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasDefaultValue(0m);

                    b.HasKey("Id");

                    b.ToTable("SubscriptionPlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Gói miễn phí – 3 lần phân tích bộ truyện và 20,000 token AI mỗi tháng.",
                            IsActive = true,
                            MaxAnalysisCount = 3,
                            MaxTokenLimit = 20000L,
                            PlanName = "Free",
                            Price = 0m
                        },
                        new
                        {
                            Id = 2,
                            Description = "Gói cơ bản – 99,000đ/tháng. 20 lần phân tích và 150,000 token AI.",
                            IsActive = true,
                            MaxAnalysisCount = 20,
                            MaxTokenLimit = 150000L,
                            PlanName = "Basic",
                            Price = 99000m
                        },
                        new
                        {
                            Id = 3,
                            Description = "Gói chuyên nghiệp – 249,000đ/tháng. 100 lần phân tích và 500,000 token AI.",
                            IsActive = true,
                            MaxAnalysisCount = 100,
                            MaxTokenLimit = 500000L,
                            PlanName = "Pro",
                            Price = 249000m
                        },
                        new
                        {
                            Id = 4,
                            Description = "Gói doanh nghiệp – 699,000đ/tháng. Không giới hạn phân tích và 2,000,000 token AI.",
                            IsActive = true,
                            MaxAnalysisCount = 9999,
                            MaxTokenLimit = 2000000L,
                            PlanName = "Enterprise",
                            Price = 699000m
                        });
                });

            modelBuilder.Entity("Repository.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("uuid_generate_v4()");

                    b.Property<string>("AvatarURL")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("DataEncryptionKey")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users", t =>
                        {
                            t.HasCheckConstraint("CK_Users_Role", "\"Role\" IN ('Admin','Author','Staff')");
                        });
                });

            modelBuilder.Entity("Repository.Entities.UserSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("PlanId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Active");

                    b.Property<int>("UsedAnalysisCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<long>("UsedTokens")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PlanId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSubscriptions", t =>
                        {
                            t.HasCheckConstraint("CK_UserSub_Status", "\"Status\" IN ('Active','Expired','Cancelled')");
                        });
                });

            modelBuilder.Entity("Repository.Entities.Chapter", b =>
                {
                    b.HasOne("Repository.Entities.ChapterVersion", "CurrentVersion")
                        .WithMany()
                        .HasForeignKey("CurrentVersionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Repository.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrentVersion");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Repository.Entities.ChapterChunk", b =>
                {
                    b.HasOne("Repository.Entities.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.ChapterVersion", "Version")
                        .WithMany("Chunks")
                        .HasForeignKey("VersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Repository.Entities.ChapterVersion", b =>
                {
                    b.HasOne("Repository.Entities.Chapter", "Chapter")
                        .WithMany("Versions")
                        .HasForeignKey("ChapterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "Creator")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Chapter");

                    b.Navigation("Creator");
                });

            modelBuilder.Entity("Repository.Entities.Project", b =>
                {
                    b.HasOne("Repository.Entities.User", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("Repository.Entities.ProjectGenre", b =>
                {
                    b.HasOne("Repository.Entities.Genre", "Genre")
                        .WithMany("ProjectGenres")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Repository.Entities.Project", "Project")
                        .WithMany("ProjectGenres")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Repository.Entities.UserSubscription", b =>
                {
                    b.HasOne("Repository.Entities.SubscriptionPlan", "Plan")
                        .WithMany("UserSubscriptions")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Repository.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Plan");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Repository.Entities.Chapter", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Repository.Entities.ChapterVersion", b =>
                {
                    b.Navigation("Chunks");
                });

            modelBuilder.Entity("Repository.Entities.Genre", b =>
                {
                    b.Navigation("ProjectGenres");
                });

            modelBuilder.Entity("Repository.Entities.Project", b =>
                {
                    b.Navigation("ProjectGenres");
                });

            modelBuilder.Entity("Repository.Entities.SubscriptionPlan", b =>
                {
                    b.Navigation("UserSubscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
